// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package store

import (
	"time"
)

type Account struct {
	ID        string       `db:"id" json:"id"`
	Name      string       `db:"name" json:"name"`
	Status    ObjectStatus `db:"status" json:"status"`
	PhoneNo   string       `db:"phone_no" json:"phone_no"`
	Gender    string       `db:"gender" json:"gender"`
	Address   string       `db:"address" json:"address"`
	CreatedAt time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt time.Time    `db:"updated_at" json:"updated_at"`
}

type Register struct {
	ID           string         `db:"id" json:"id"`
	ParentID     string         `db:"parent_id" json:"parent_id"`
	StudentID    string         `db:"student_id" json:"student_id"`
	Status       RegisterStatus `db:"status" json:"status"`
	RegisterTime time.Time      `db:"register_time" json:"register_time"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updated_at"`
}

type StudentParent struct {
	ID        int64        `db:"id" json:"id"`
	ParentID  string       `db:"parent_id" json:"parent_id"`
	StudentID string       `db:"student_id" json:"student_id"`
	Status    ObjectStatus `db:"status" json:"status"`
	CreatedAt time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt time.Time    `db:"updated_at" json:"updated_at"`
}

type Transaction struct {
	ID         int64      `db:"id" json:"id"`
	RegisterID string     `db:"register_id" json:"register_id"`
	ActionType ActionType `db:"action_type" json:"action_type"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
}
